-- 게시판 테이블 생성 mysql
CREATE TABLE TBL_BOARD (
BNO INT NOT NULL,
TITLE VARCHAR(200) NOT NULL,
CONTNET VARCHAR(4000),
WRITER VARCHAR(50) NOT NULL,
REGDATE DATETIME DEFAULT NOW(),
VIEWCNT INT DEFAULT 0,
PRIMARY KEY (BNO)
)
