CREATE TABLE TBL_REPLY (
	RNO INT auto_increment,
    BNO INT NOT NULL,
    REPLYTEXT VARCHAR(1000) NOT NULL,
    REPLYER VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    REGDATE DATETIME DEFAULT NOW(),
    UPDATEDATE DATETIME DEFAULT NOW(),
    PRIMARY KEY (RNO)
) 

-- utf8이 최신 흐름에 따라 변경되어 테이블을 utf_general_ci에서 ut8_unicode_ci로 변경
ALTER TABLE TBL_MEMBER convert to CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI;
ALTER TABLE TBL_BOARD convert to CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI;
ALTER TABLE TBL_REPLY CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;