CREATE TABLE TBL_MEMBER (
	USER_ID VARCHAR(50),
    USER_PW VARCHAR(30),
    USER_NAME VARCHAR(100),
    USER_EMAIL VARCHAR(100),
    USER_REGDATE DATETIME DEFAULT NOW(),
    USER_UPDATEDATE DATETIME DEFAULT NOW(),
    PRIMARY KEY(USER_ID)
);

INSERT INTO TBL_MEMBER(USER_ID, USER_PW, USER_NAME, USER_EMAIL) VALUES ('aaa', '1234', '에이에이에이', 'dd@dd.dd');
INSERT INTO TBL_MEMBER(USER_ID, USER_PW, USER_NAME, USER_EMAIL) VALUES ('bbb', '1234', '비비비', 'bb@bb.bb');