CREATE TABLE TBL_ATTACH (
	FULLNAME VARCHAR(150) NOT NULL,
    BNO INT AUTO_INCREMENT,
    REGDATE DATETIME DEFAULT NOW(),
    PRIMARY KEY(BNO, FULLNAME)
);

ALTER TABLE TBL_ATTACH ADD CONSTRAINT FK_BOARD_ATTACH FOREIGN KEY(BNO) REFERENCES TBL_BOARD(BNO);
