CREATE TABLE TBL_ADMIN (
	USER_ID VARCHAR(50) NOT NULL,
    USER_PW VARCHAR(50) NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL,
    USER_EMAIL VARCHAR(100),
    USER_REGDATE DATETIME DEFAULT NOW(),
    USER_UPDATEDATE DATETIME DEFAULT NOW(),
    PRIMARY KEY(USER_ID)
);

INSERT INTO TBL_ADMIN(USER_ID, USER_PW, USER_NAME, USER_EMAIL) VALUES ('admin', '1234', '관리자', 'admin@admin.com');