CREATE TABLE TBL_USER (
	USERID VARCHAR(50) NOT NULL,
    USERPW VARCHAR(50) NOT NULL,
    UNAME VARCHAR(100) NOT NULL,
    UPOINT NUMERIC DEFAULT 0,
    PRIMARY KEY (USERID)
);

INSERT INTO TBL_USER (USERID, USERPW, UNAME)
VALUES ('user01', '1234', 'kim');

INSERT INTO TBL_USER (USERID, USERPW, UNAME)
VALUES ('user02', '1234', 'lee');

INSERT INTO TBL_USER (USERID, USERPW, UNAME)
VALUES ('user03', '1234', 'park');

INSERT INTO TBL_USER (USERID, USERPW, UNAME)
VALUES ('user04', '1234', 'choi');

INSERT INTO TBL_USER (USERID, USERPW, UNAME)
VALUES ('user05', '1234', 'yoon');

INSERT INTO TBL_USER (USERID, USERPW, UNAME)
VALUES ('user06', '1234', 'yang');

INSERT INTO TBL_USER (USERID, USERPW, UNAME)
VALUES ('user07', '1234', 'cho');

INSERT INTO TBL_USER (USERID, USERPW, UNAME)
VALUES ('user08', '1234', 'koo');

COMMIT;